import type {Metadata} from "next";
import "./globals.scss";
import Layout from "@/components/layout";
import StateProvider from "@/context";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en">
        <body>
        <StateProvider>
            <Layout>
                {children}
            </Layout>
        </StateProvider>
        </body>
        </html>
    );
}
